### ISSUE TITLE
Call to undefined method PHPUnit_Util_Configuration::getTextGroupConfiguration()

### ISSUE THREAD

**Issue by wpdeveloper10** [10up/wp_mock#106]
hey,
I have cloned this repository, everytime when i try to run phpunit from root folder it throws 
Call to undefined method PHPUnit_Util_Configuration::getTextGroupConfiguration() in /vendor/phpunit/phpunit/src/TextUI/TestRunner.php on line 1066.

What could be the issue?

**Comment by ericmann** [comment]
> everytime when i try to run phpunit from root folder

Are you using the PHPUnit loaded by Composer, or a version installed globally?

**Comment by sudar** [comment]
@wpdeveloper10 

If you have installed `phpunit` through composer then run `vendor/bin/phpunit` instead of just `phpunit`.
