### ISSUE TITLE
Move to tagged releases, please

### ISSUE THREAD

**Issue by sciamannikoo** [10up/wp_mock#107]
Hello.

I've just found that in #82 you aren't currently using tagged releases.

While we could use `dev-dev` in our projects, we prefer to use tags with all the external libraries, so to lock the versions to minor ones, even when a developer (mistakenly) type `composer update`.

It's hard to educate all developer to only update the libraries they want to use and relying on "dev" may cause backwards compatibilities which would not happen by using, for instance `~1.0`.

Now, since we need what's in "dev", we will probably switch to it, for the time being, after checking that all our existing tests still work, but it would be great if the tag approach could be used before any new breaking change is added to the development.

**Comment by johnpbloch** [comment]
WP Mock is currently not stable software. As with all pre-1.0 software, I can only suggest that you use a released minor version or that you use a development branch.

@ericmann might we tag another 0.x.0 release in the meantime?
