### ISSUE TITLE
Test that filter was invoked

### ISSUE THREAD

**Issue by leewillis77** [10up/wp_mock#109]
Hi; 

I'm looking at WP_Mock for adding unit testing to some plugins I maintain. I've read through the docs, but can't see whether I'm missing something or whether what I'm looking to do isn't supported. 

I want to verify that when I call a method on my class that it invokes a filter, e.g. I want to test that this is happening:

``` apply_filters( 'some_filter_name', $some_data ); ```

I tried `expectAction()` in case that also worked for filters, but it doesn't seem to. I've also seen onFilter, but that only seems to allow you to provide a filtered value, without asserting that the filter is actually ever called. 

Is there a way of doing this (I'd expect it to be `WP_Mock::expectFilter()`) ?

**Comment by ericmann** [comment]
There are some examples posted [in the Readme](https://github.com/10up/wp_mock#asserting-that-actions-and-filters-are-applied)

**Comment by leewillis77** [comment]
Hi @ericmann 

Thanks for your reply, however as I said in my original post:

> I've also seen onFilter, but that only seems to allow you to provide a filtered value, without asserting that the filter is actually ever called.

I understand that you can use `onFilter` to attach to a filter. In the example in the readme, you implement an `onFilter`, retrieve the filtered value, and then check the value matches what you filtered it to be. This seems wasteful in terms of code required, and is also dependent on the processed filter value being available to the test (in your case it's the return value of the method under test).

So, you cannot use this approach to check that a filter was called, *unless* the results of the filter are returned from the method under test. 

What I'm looking for here is something simple like the `expectAction` method, but for filters, e.g. 

```
function test_action_calling_function () {
	\WP_Mock::expectFilter( 'my_filter' );
	method_under_test();
}
```
