### ISSUE TITLE
Add a strict mode

### ISSUE THREAD

**Issue by johnpbloch** [10up/wp_mock#11]
This will be off by default.

Currently, if a function is defined by WP_Mock and has no expectations defined, it will run as a no-op function with a return value of `null`. We need a strict mode that will cause failure if a function is used without an explicit expectation. This will also cause `add_action` and `add_filter` to fail without an explicit expectation (currently the do not fail if unexpected).

**Comment by sirbrillig** [comment]
Is there a plan for how to enable strict mode? Something global like `\WP_Mock::enable_strict_mode()`? 

(Asking because I'd be happy to start implementing this.)
