### ISSUE TITLE
Mocking static methods

### ISSUE THREAD

**Issue by merianos** [10up/wp_mock#115]
Hello,

starting by saying that I am totally new on Unit testing and thus my question it could be wrong. So I say a big sorry if I just spend your time.

Currently, I initiated a new theme for development using unit testing. Until now I guess I am fine with what I did, and all are green, while the Code Coverage report is also totally green.

The question I have to ask is related to `Kirki` plugin.

Using unit testing, I'd like to mock the static method call:

```
Kirki::add_config(
    'mc',
    [
        'capability' => 'edit_theme_options',
        'option_type' => 'theme_mod'
    ]
);
```

My current code in the test is like that:

```
// Get my theme entry point class instance
$app          = App::getInstance();
// Get the configuration class instance from the Container
$configurator = $app->get_service( 'configurator' );

// Mock the static method call
\WP_Mock::userFunction(
    'Kirki::add_config',
    [
        'args' => [
            'capability'  => 'edit_theme_options',
            'option_type' => 'theme_mod',
        ]
    ]
);

// Run the method in my configuration class that using the Kirki::add_config method.
$configurator->setup_theme_configuration();
```

The error I get in my console is the following:

```
1) Test\MC_App\Theme\ConfiguratorTest::vaidate_kirki_configuration_options
ParseError: syntax error, unexpected '::' (T_PAAMAYIM_NEKUDOTAYIM), expecting '('
```

**Note:** I have also try the following way to call the static method `[ 'Kirki', 'add_config' ]` but also doesn't work.

**Comment by johnpbloch** [comment]
Hi @merianos, thanks for stopping by! The testcase class provides this functionality (not really a logical place for the functionality to live, but that's where it is...):

```php
$this->mockStaticMethod( 'Kirki::add_config' )
     ->with( [ 'capability' => 'edit_theme_options', 'option_type' => 'theme_mod' ] );
```

This assumes two things: first, you're using the testcase packaged with wp mock (I think you have to do so for wp mock to work, so that should be the case already), and second, that you're using patchwork. If not, [check out the section of the docs on bootstrapping with patchwork](https://github.com/10up/wp_mock#bootstrapping-wp_mock).

**Comment by merianos** [comment]
Hello, @johnpbloch and thank you for your fast response.

So I have tried all you have described but yet I have issues.

So, I changed my test class signature from:

```
class ConfiguratorTest extends BaseTestCase
```
to
```
class ConfiguratorTest extends WP_Mock\Tools\TestCase
```

and in my bootstrap.php I have the change this code:
```
WP_Mock::bootstrap();
```
to this:
```
WP_Mock::setUsePatchwork( true );
WP_Mock::bootstrap();
```

but the output of the PHPUnit test is this:
```
Patchwork is not loaded! Please load patchwork before mocking static methods!
```

I also have tried to run the `setUserPatchwork` from within the test method body, but yet the same issue.

Am I doing anything wrong?

Thanks in advance!! :smiley:

**Comment by merianos** [comment]
Any idea on how to solve that issue?

I have modified the `10up/wp_mock/php/WP_Mock/Tools/TestCase.php` in the line `167` to see what are the values of the statements `WP_Mock::usingPatchwork()` and `function_exists( 'Patchwork\Interceptor\patch' )` and the response is `true` and `false` accordingly.

Unfortunately, I cannot locate somewhere the `PAtchwork\Interceptor\patch`. I have searched my vendor directory as well on the web and there's no reference to this function.

Can you help, please?

Thanks in advance.

**Comment by merianos** [comment]
So I found my solution using [Mockery](https://github.com/mockery/mockery).

The way I test the static methods of Kirki are like this:

```
$kirki = \Mockery::mock( 'overload:Kirki' );

$kirki
    ->shouldReceive( 'add_config' )
    ->once()
    ->withArgs(
        [
            'mc',
            [
		'capability'  => 'edit_theme_options',
		'option_type' => 'theme_mod',
            ],
        ]
    )

$myConfigClass = new ConfigClass();
$myConfigClass->the_method_registering_the_kirki_config();
```

Hope this is useful for other developers too.
