### ISSUE TITLE
Tests marked as risky, but not using deprecated methods

### ISSUE THREAD

**Issue by samiam236** [10up/wp_mock#118]
When I write a passing test like the below, I get a risky test message from PHPUnit.

```
public function test_should_init_shortcodes() {
    $bookingShortcodes = new Booking_Shortcodes();
    $initClass = new Shortcodes_Init($bookingShortcodes);

    \WP_Mock::userFunction( 'add_shortcode', array(
      'args' => ['book-now', [$initClass->bookingShortcodes, 'book_now']],
      'times' => 1
    )	);
    
    $initClass->init();
  }
```

Here is the message from PHPUnit:
```
There was 1 risky test:

1) Shortcodes_Init_Test::test_should_init_shortcodes
This test did not perform any assertions
```

I know this is expected when using `WP_Mock::wpFunction()`, but am I doing something wrong here that's triggering the message when using `WP_Mock::userFunction()`?

**Comment by johnpbloch** [comment]
The risky test message tells you it's because you're not using assertions.
Adding `$this->assertConditionsMet()` at the end of the method ought to get
rid of the risky test.

**Comment by samiam236** [comment]
Thanks @johnpbloch that makes perfect sense!
