### ISSUE TITLE
Improve how argument matching works for hook expectations

### ISSUE THREAD

**Issue by johnpbloch** [10up/wp_mock#12]
Currently you can't declare expectations on things like type or fuzzy matching for arguments. If the args don't match exactly, we can't match an action or filter. I'd like to be able to do something like

``` php
WP_Mock::expectActionAdded( 'some_action', array( WP_Mock::typeMatcher( 'SomeClass' ), 'method' ) );
new SomeClass(); // Action added in constructor
```

**Comment by ericmann** [comment]
Closing for now. Been a while since this has come up. Can re-open or create a new thread if we need to revisit.
