### ISSUE TITLE
This test did not perform any assertions

### ISSUE THREAD

**Issue by andreasciamanna** [10up/wp_mock#124]
This should be probably considered as a follow-up of #118.

As [suggested](https://github.com/sebastianbergmann/phpunit/issues/2071) in [other](https://github.com/phpspec/prophecy/issues/366) cases, shouldn't WP_Mock tell PHPUnit how to deal with the assertions?

For instance, by calling `\PHPUnit\Framework\TestCase::addToAssertionCount`.

I think that would be cleaner than adding `$this->addToAssertionCount( 1 );` everywhere in our tests.

By the way, the suggestion of calling `$this->assertConditionsMet()` in the original issue doesn't work, because this method does not exist.

In case it's needed, here's an example:

```php
/**
 * @test
 */
public function it_enqueue_and_localize_scripts() {
	$subject = new WPML_Browser_Redirect( $this->mock_sitepress() );
	$should_enqueue = true;
	WP_Mock::onFilter( 'wpml_browser_redirect_language_params' )
		   ->with( $this->params )
		   ->reply( $this->params );
	WP_Mock::userFunction( 'wp_localize_script', array(
		'args' => array(
			'wpml-browser-redirect',
			'wpml_browser_redirect_params',
			WP_Mock\Functions::type( 'array' ),
		)
	) );
	WP_Mock::onFilter( 'wpml_enqueue_browser_redirect_language' )
		   ->with( true )
		   ->reply( $should_enqueue );
	WP_Mock::userFunction( 'wp_enqueue_script', array(
		'args' => array(
			'wpml-browser-redirect',
		)
	) );
	WP_Mock::expectAction( 'wpml_enqueued_browser_redirect_language', $should_enqueue, $this->params );
	$subject->enqueue_scripts();
}
```

To workaround the problem, I need to add `$this->addToAssertionCount( 1 );` at the end of the test.

**Comment by johnpbloch** [comment]
Hi, thanks for stopping by.

Are you extending `\WP_Mock\Tools\TestCase`? Extending the it will give you access to `$this->assertConditionsMet()` as well as a number of other helpful tools.

I just checked and although all the example test cases do extend the WP_Mock class, it's never explicitly stated as a requirement, or even option. I'd also thought I'd added code that failed any tests not extending the WP_Mock test case, but I guess that never made it in.

I think what we have here is a documentation problem.

**Comment by andreasciamanna** [comment]
I've been using WP_Mock for at least a couple of years and only now I realise I've been doing it wrong! :)

Thanks for the tip!
