### ISSUE TITLE
When mocking wp_die the method keeps on executing

### ISSUE THREAD

**Issue by dingo-d** [10up/wp_mock#126]
I am testing a method, used as an ajax callback, which has a validation check inside.

The validation part looks like this

```php
/*
 * Validation check.
 */
if ( ! isset( $_POST['myKey'] ) ) {
  $response = 'Some error'; // Originally I have `esc_html__` here which is mocked.
  \wp_die( \wp_json_encode( $response ) ); // wp_json_encode is aliased with json_encode.
}
```

In my test I've mocked the `wp_die` function like this

```php
\WP_Mock::userFunction( 'wp_die', array(
    'times' => 1,
    'return_arg' => 0,
) );
```

But the test fails because it seems that the execution of the callback method goes on (nonce verification and other functionality).

I'm puzzled as to why this happens. Since my `wp_die` should __return__ the first argument that is passed to it (`\wp_json_encode( $response )`), which should exit the method, and the test should pass. When I turn the coverage report, the part that checks if it's set (validation), and the `wp_die` is green, but then the rest fails, because I have an `Undefined index: myKey` (triggered by the nonce check).

Is there some extra functionality I'm missing in the `userFunction`?

**Comment by DevWael** [comment]
@dingo-d were you able to manage this?

**Comment by dingo-d** [comment]
Ufff, this was back in 2018, I'm no longer using wp_mock for mocking. These days I use [Brain Monkey](https://github.com/Brain-WP/BrainMonkey) for all the unit test mocking purposes, or just do the native integration tests via [WP Test Utils](https://github.com/Yoast/wp-test-utils).
