### ISSUE TITLE
Is it possible to test actions and filters that use instance methods as callbacks?

### ISSUE THREAD

**Issue by wujekbogdan** [10up/wp_mock#127]
Let's assume that I'd like to test if the `filterHttpOrigin` filter is added when a new instance of `MyClass` is created

``` php
class MyClass
{
    public function __construct()
    {
        add_filter('http_origin', [$this, 'filterHttpOrigin']);
    }

    public function filterHttpOrigin($origin)
    {
        // Do something
    }
}
```

First I tried to do the following but without success. 

``` php
use \WP_Mock\Tools\TestCase;
class MyClassTest extends TestCase
{
    public function testConstructor()
    {
        $myClassInstance = new MyClass();
        \WP_Mock::expectFilterAdded('http_origin', [$myClassInstance, 'filterHttpOrigin']);
    }
}
```

I got an error:

> Mockery\Exception\InvalidCountException : Method intercepted(<Any Arguments>) from Mockery_0__intercept should be called at least 1 times but called 0 times.

Which is understandable because the constructor is called before the `expectFilterAdded` is called. 

So I also tried a different approach - I introduced an `init` method instead of initializing the filter within the constructor:

``` php
class MyClass
{
    public function __construct() { }

    public function init() {
        add_filter('http_origin', [$this, 'filterHttpOrigin']);
    }

    public function filterHttpOrigin($origin)
    {
        // Do something
    }
}
```

But the following test doesn't work either. In this case I'm getting an error message:

> This test did not perform any assertions

``` php
use \WP_Mock\Tools\TestCase;

class MyClassTest extends TestCase
{
    public function testConstructor()
    {
        $myClassInstance = new MyClass();
        \WP_Mock::expectFilterAdded('http_origin', [$myClassInstance, 'filterHttpOrigin']);
        $myClassInstance->init();
    }
}
```

Am I doing something wrong? Is it a bug?

---
**UPDATE**

The second, refactored example actually works fine. The only thing that was missing there was the call to `$this->assertConditionsMet();` function - that "tells" PHPUnit that assertion was performed.

BTW, It would be good to update the docs with this information. It's not that obvious that `\WP_Mock::expectFilterAdded` and `\WP_Mock::expectActionAdded` are not assertions.

**Comment by ericmann** [comment]
We've made some changes to the filter/action expectations and assertions that _might_ address this? If the refactored code works I'll keep this closed for now.

**Comment by dinhtungdu** [comment]
@wujekbogdan You can also add expectations to assertion count in the `tearDown` of the test class instead of calling `$this->assertConditionsMet();`.
```
public function tearDown(): void {
    $this->addToAssertionCount(
        \Mockery::getContainer()->mockery_getExpectationCount()
    );
    \WP_Mock::tearDown();
}
```
