### ISSUE TITLE
Fatal error: Uncaught Error: Call to a member function setTestResult() on null when run in Eclipse

### ISSUE THREAD

**Issue by agmckee** [10up/wp_mock#128]
Version 0.3.0 
PHP 7.0.32 (yes, I know it is an older version of PHP but I am using it for a reason)
PHPUnit 6.5.13

Followed the setup guide mostly - added setUp and tearDown to test case extending `WP_Mock\Tools\TestCase`. No need to add the autoloader as Eclipse takes care of that and `WP_Mock::setUp()` does the bootstrap if not already bootstrapped.

However when running the test it fails with "Fatal error: Uncaught Error: Call to a member function setTestResult() on null". The null is the value of the `$deprecated_listener` property which doesn't appear to be set unless the class is bootstrapped. Why isn't the class bootstrapped? It doesn't look like setUp gets called. If I add `parent::run($result)` to line 303 of `WP_Mock\Tools\TestCase` it works as expected.

I was also able to recreate this on the command line interface of PHPUnit, so Eclipse doesn't seem to be doing anything strange to cause this issue.

**Comment by ericmann** [comment]
Older version of the tool, PHP, and PHPUnit. If this is still an issue, let's go ahead and open a new ticket here but for now I'm closing this.

**Comment by BrianHenryIE** [comment]
In PHPStorm, adding `--bootstrap tests/bootstrap.php` to _Test Runner options_ remedied this for me. PHPUnit 7.5.7, PHP 7.3.0b2.

**Comment by AdamMarton** [comment]
This is still the case (and @agmckee 's solution still resolves the issue) on PHPUnit ^8.3 and latest WP_Mock.
