### ISSUE TITLE
Attempting to mock plugin template tags with WP_Mock::userFunction

### ISSUE THREAD

**Issue by CTaylorGuitar** [10up/wp_mock#131]
My wordpress plugin provides some template tags from a single file and I am trying to test them.  In the example below I am testing a() and I want to mock b(), which is called by a().

I get an error message 'Call to undefined function c()' so it seems my attempt to mock b() with WP_Mock::userFunction is failing.

Is this the expected behaviour?  How can I make a test double for b()?

my-plugin-template-tags.php
````
<?php 

function a(){
    $val = b();
    return 'bar';
}

function b(){
    c();
}
````

TemplateTagsTest.php
````
<?php

declare(strict_types=1);

use PHPUnit\Framework\TestCase;

final class TemplateTagsTest extends TestCase
{
    public function test_a()
    {
        \WP_Mock::userFunction( 'b', array(
            'return' => 'foo'
        ) );

        $this->assertSame( 'bar', a() );
    }
    
    public function setUp() : void
    {
        \WP_Mock::setUp();
    }
    public function tearDown() : void
    {
        \WP_Mock::tearDown();
    }
}

**Comment by ericmann** [comment]
I'm worried that your code is far too simplified here from what you've actually got in your project. The way you've written it here, it doesn't matter _what_ `b()` does as `a()` will always return `'bar`'. If you're only trying to test whether or not `c()` is being called ... I'm really not sure what you're trying to accomplish here.

**Comment by CTaylorGuitar** [comment]
Bootstrapping phpunit includes my-plugin-template-tags.php as you would expect.  When a() is called inside the assert, b() is in scope too, because it is in the same file as a().

I don't want to call the real b() when testing a() I would like to mock it.  My call to WP_Mock::userFunction() isn't having an affect however which is indicated by the fatal error.

How can I mock b()?

**Comment by johnpbloch** [comment]
@CTaylorGuitar It sounds like you don't have Patchwork turned on. See [the documentation on bootstrapping](https://github.com/10up/wp_mock#bootstrapping-wp_mock) for more detail, but the short answer is that you need to add

```php
WP_Mock::setUsePatchwork( true );
```

to your bootstrap file ***before*** you run `WP_Mock::bootstrap()`.

**Comment by johnpbloch** [comment]
If you *are* already loading patchwork, perhaps you're not fully qualifying `b()` when mocking it. If you're using namespaces you must provide the fully-qualified name of functions you want to mock, even if the tests share a namespace with the SUT.

Like Eric said, your pseudo-code is giving us an idea of what you want to do and a general idea of what is going wrong, but it's not giving us enough information regarding what specifically is causing `userFunction` to fail to override your function properly. That said, I can't think of any other reasons userFunction would be failing beside a lack of patchwork being loaded or a non-qualified function reference. If neither of these apply to you, we'll need to see the actual tests and the actual SUT (or at least, something much closer to it) to figure out the issue.

**Comment by CTaylorGuitar** [comment]
With patchwork turned on the issue is resolved.  Many thanks.
