### ISSUE TITLE
assertHooksAdded does not actually assert

### ISSUE THREAD

**Issue by rocketcrazy07** [10up/wp_mock#134]
When using assertHooksAdded an assertion is not actually called and causes a risky test using phpunit 7.5.4+.  I am willing to fix an put in a pull request but need to wait for my previous pull request otherwise the build will fail.  Putting this in to remind myself so I can quickly fix issue when other pull request has been accepted.

**Comment by ericmann** [comment]
Other PR has been accepted and merged. Anything left to do here?

**Comment by rocketcrazy07** [comment]
Nope that was it thanks.
