### ISSUE TITLE
testing wp_enqueue_style and wp_enqueue_script

### ISSUE THREAD

**Issue by nan140114** [10up/wp_mock#135]
Is it possible to test `wp_enqueue_script` and `wp_enqueue_script` functions with wp_mock?. My coverage test is showing that the next lines are uncovered

```php
function seed_front_theme_style()
{
  wp_enqueue_style(
    'seed-css',
    plugins_url() . '/cafeto-seed-wordpress-plugin/assets/css/main.css'
  );
  wp_enqueue_script(
    'seed-js',
    plugins_url('/cafeto-seed-wordpress-plugin/assets/js/main.js', __FILE__)
  );
}

add_action( 'wp_enqueue_scripts', 'cael_student_selfserv_front_theme_style' );
```

But, i don't know how to test that WP functions. Thanks in advance.

**Comment by ericmann** [comment]
WP_Mock is for testing _your_ custom code, not core WordPress functionality. You'd use this library to _mock_ the core functions, not to test them directly.

**Comment by nan140114** [comment]
Thank you!
