### ISSUE TITLE
readme updates

### ISSUE THREAD

**Issue by jeffpaul** [10up/wp_mock#139]
**Is your feature request related to a problem? Please describe.**
It's not obvious the level of support provided for this repo, so let's add some clarification.

**Describe the solution you'd like**
- [x] add support level section and badge
~- [ ] add release version badge~
- [x] add license badge

**Describe alternatives you've considered**
none.

**Additional context**
n/a

**Comment by jeffpaul** [comment]
As there's no tagged and numbered release, I'll skip the release version badge for now.

**Comment by jeffpaul** [comment]
Also, not 100% certain but [this](https://github.com/10up/wp_mock/blob/master/LICENSE.md) appears to be GPLv2, though would be good to get clarification on that before adding in a GPLv2 license badge.

**Comment by ericmann** [comment]
@jeffpaul The project is GPLv2 or any later version -> https://github.com/10up/wp_mock/blob/master/composer.json#L4
