### ISSUE TITLE
\WP_Mock::userFunction() with a double as argument fails when the mocked function does not use a hardcoded double

### ISSUE THREAD

**Issue by koengabriels** [10up/wp_mock#148]
To be able to unit test the validation of an AJAX call through a private method I mock all the WP functions, including the wp_send_json_success and wp_send_json_error functions because they are expected to run for a valid and invalid request respectively.

For my test I know the data to send back with the response is 8.54 and the statuscode will be 200, however I get the following error:

> No matching handler found for Mockery_0__wp_api::wp_send_json_success(8.54, 200). Either the method was unexpected or its arguments matched no expected argument list for this method

When I var_dump the variable passed to the data argument for wp_send_json_success it is correctly shown as 

> double(8.54)

If I change my code to pass 8.54 hardcoded to wp_send_json_success it works.

Below is the code that produces the error.
(partial) code for the test:
```
\WP_Mock::userFunction(
	'wp_send_json_success',
	array(
		'args' => array( 8.54, 200 ),
		'times' => 1
	)
);

$plooiwerk_calculator->ajax_calculate_price_per_unit();
```

code being tested:
```
public function ajax_calculate_price_per_unit() {
	if( $this->is_valid_calculate_price_per_unit_ajax_call() ) {
		$price_per_unit = $this->calculate_price_per_unit(
			get_query_var( 'sides' ),
			get_query_var( 'fold_price' ) ,
			get_query_var( 'extra_costs' )
		);
		wp_send_json_success(  $price_per_unit, 200 );
	} else {
		wp_send_json_error( 'Invalid request', 400 );
	}
}
```
If I change $price_per_unit to 8.54 in the call to wp_send_json_success arguments list it works, if I change the value 8.54 in the userFunction() to '8.54' and pass stringval( $price_per_unit ) to the wp_send_json_success arguments list it also works.

Any help is appreciated. Thanks in advance.

**Comment by rneudorf-godaddy** [comment]
@koengabriels I am not longer able to replicate this issue, it's quite old. Could you provide more context (ex. the entire test) if you are still seeing this.

**Comment by rneudorf-godaddy** [comment]
@koengabriels I am going to close this issue as it seems like it may no longer be relevant.

**Comment by koengabriels** [comment]
@rneudorf-godaddy sorry for not responding earlier, I overlooked the email notifications.
Should I run into the same issue again (project where this happened has been put on hold), I will create a new issue and link it to this one.
Thanks for looking into it!
