### ISSUE TITLE
Patchwork not loaded

### ISSUE THREAD

**Issue by koengabriels** [10up/wp_mock#150]
When I setUsePatchWork to true in bootstrap like this:
`WP_Mock::setUsePatchwork( true );
WP_Mock::bootstrap();`

And mock a static method like this:
`$this->mockStaticMethod('Tm_Extra_Options_Form_Wrapper::product_has_global_options')
			->with(5)->andReturn(true);`

The unit tests throw an exception:
`Exception : Patchwork is not loaded! Please load patchwork before mocking static methods!`

I am using wp_mock version 0.4.2 with Patchwork version 2.1.11

When looking for a solution I came across the same issue here but it was already closed due to no other users reporting it. #116 
There is also another issue #115 where the reporter decided to not use patchwork because of the same problem.

Any help is greatly appreciated

**Comment by koengabriels** [comment]
Update: I var_dumped `WP_Mock::usingPatchwork()` right before calling mockStaticMethod, it does return true which seems odd

`function_exists( 'Patchwork\Interceptor\patch' )` does return false to that is why the exception is thrown from what I can see being unfamiliar with code base of wp_mock and it's dependencies

**Comment by over-engineer** [comment]
Any updates on this?
