### ISSUE TITLE
WP_Mock breaks with PhpUnit >= 9.5.0

### ISSUE THREAD

**Issue by ChrisWiegman** [10up/wp_mock#158]
**Describe the bug**
Phpunit 9.5 refactors the test case and removesd the `getAnnotations` method causing wp_mock tests to fail.

**To Reproduce**
1. Update Phpunit to 9.5.0
2. Run any test

**Expected behavior**
Tests should run successcully

**Screenshots**

```Error: Call to undefined method <test class>::getAnnotations()```

**Comment by vyskoczilova** [comment]
Any update on this issue?

**Comment by romanmartushev** [comment]
Update on this issue?

**Comment by kudinovfedor** [comment]
Hello.
I could not select and specify a reviewer.
Added a fix for this problem #164

**Comment by fiskhandlarn** [comment]
any news on this? are you guys looking for new maintainers, @jeffpaul ?

**Comment by jeffpaul** [comment]
@fiskhandlarn if you can help review https://github.com/10up/wp_mock/pull/164 that would be great!

**Comment by fiskhandlarn** [comment]
@jeffpaul i just tried and it works. will write details in https://github.com/10up/wp_mock/pull/164

**Comment by XedinUnknown** [comment]
Pardon the necromancy, I'll be happy to open a new issue if needed, but I just reproduced this with `0.5.0`. Regression?
