### ISSUE TITLE
Change license from GPL 2.0 to BSD-3-Clause

### ISSUE THREAD

**Issue by unfulvio-godaddy** [10up/wp_mock#198]
## Proposal

Currently WP_Mock has some inconsistency over its OSS license.

LICENSE.MD bundles GPL-2.0; composer.json mentions GPL-2.0-or-later (so, 3.0?); meanwhile the main WP_Mock class states the license is MIT.

We need bring all of these consistent, but probably we could also take the opportunity to re-evaluate which license would serve WP_Mock, its contributors, and its users best.

I would propose to switch WP_Mock to BSD-3-clause license consistently across the project. 

In the end if a project using WP_Mock is building WordPress code, they should be already employing GPL, since WordPress is GPL. WP_Mock per se does not need to bundle or run WordPress to function, does not build on top of WordPress from a technical standpoint. Rather, you could argue, over Mockery or PhpUnit, which both use BSD-3-Clause (or, to an extent, Patchwork, which uses MIT).

The BDS-3-clause license is very similar to MIT, and very permissive, and consists only of the following:

```
Copyright <YEAR> <COPYRIGHT HOLDER> <-- in case of WP_Mock this would be the contributors: you all!

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
```

Reasons why I would like to propose this change:

1. It's a very easy to understand OSS license compatible with the current principles WP_Mock was built.
2. It allows redistribution of WP_Mock in any form, for commercial and OSS projects, may help companies adopting WP_Mock as part of their toolset.
3. Protects the copyright of the project to its contributors - just like now in LICENSE.md we could just point to the list of contributors.
4. Also protects contributors themselves with its clause n.3.

Since this change would affect past contributors, I need to ask for their agreement. I will ping them below in case they'd like to discuss this.

I would also set a deadline for this decision, say in a ~6 months time frame from now (Jan 10 2023).

CC  
@jeffpaul @ericmann @johnpbloch @nicolqs @khadiwaa @codebykat @jeffsebring @gmazzap @goblindegook @stevegrunwell @sudar @tfrommen @dsawardekar @GaryJones @sirbrillig @petenelson @tlovett1 @mathieuhays @lkwdwrd @cmmarslender @bswatson @krodyrobi @psafarov @ocularrhythm @rdeeb @rocketcrazy07 @BrianHenryIE @over-engineer @kudinovfedor @jigneshnakrani088 @phatsk @ohryan @wvega @unfulvio @ashleyfae

apologies if I forgot anyone!

**Comment by GaryJones** [comment]
Fine with me 👍🏻

**Comment by stevegrunwell** [comment]
As long as the licenses are compatible, no issue on my end.

**Comment by bswatson** [comment]
👍 from me.

**Comment by tfrommen** [comment]
👋🤠👍

**Comment by ericmann** [comment]
No objections here.

**Comment by BrianHenryIE** [comment]
I'm ok with that.

**Comment by sudar** [comment]
Fine with me as long as the licenses are compatible.

**Comment by lkwdwrd** [comment]
Fine by meOn Jan 10, 2023, at 6:21 PM, Sudar Muthu ***@***.***> wrote:﻿
Fine with me as long as the licenses are compatible.

**Comment by ajaynes-godaddy** [comment]
@cj-watts (formerly rocketcrazy07)

**Comment by ashleyfae** [comment]
Fine with me.

**Comment by jigneshnakrani088** [comment]
Fine by me 👍

**Comment by jeffpaul** [comment]
[10up's preferences in licensing](https://10up.github.io/Open-Source-Best-Practices/releasing/#licensing) is to use GPLv2 for WordPress plugins and themes and to use MIT for all other projects.  Given that WP_Mock is not a WordPress plugin or theme, there's no **need** for it to be GPLv2.  Also if WP_Mock happened to be bundled in a distributed WordPress plugin or theme, then as long as WP_Mock's license is GPL-compatible it would not disrupt the bundling plugin or theme's ability to license the entire package as GPLv2.  The `BSD-3-Clause` license is GPL-compatible.  So while my personal preference in this case would have been to go with `MIT`, everyone else on this thread is aligned to `BSD-3-Clause` and as such I will relent given that `BSD-3-Clause` still aligns with 10up's broad expectations for licensing open source code.

For the actual resulting PR, the following are the places I see that will need to be updated to state `BSD-3-Clause` (or the [actual license file information](https://github.com/10up/wp_mock/community/license/new?branch=trunk&filename=LICENSE&template=bsd-3-clause)):

1. https://github.com/10up/wp_mock/blob/e5ac387ca2ef110750b64ab8a7294dce200a5f54/README.md?plain=1#L5
2. https://github.com/10up/wp_mock/blob/e5ac387ca2ef110750b64ab8a7294dce200a5f54/composer.json#L4
3. https://github.com/10up/wp_mock/blob/e5ac387ca2ef110750b64ab8a7294dce200a5f54/php/WP_Mock.php#L31
4. https://github.com/10up/wp_mock/blob/trunk/LICENSE.md
5. https://github.com/10up/wp_mock/blob/e5ac387ca2ef110750b64ab8a7294dce200a5f54/php/WP_Mock.php#L5-L27

P.S. - The `GPL-2.0-or-later` license identifier does not equate specifically to GPLv3, but rather any GPL version from v2 onward (so could be v2 OR v3).  This is _usually_ the actual GPL license that 10up tends to utilize on WordPress plugin and theme projects.

**Comment by unfulvio-godaddy** [comment]
Thank you all and @jeffpaul for chiming in. 

Since about 6 months have passed after I brought this up to the community and past/present contributors, I think it's time we can make this change in light of upcoming v1 release. Here's the relevant PR: https://github.com/10up/wp_mock/pull/218

Thanks again!
