### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by johnpbloch** [10up/wp_mock#20]
We are not doing well in this regard...

**Comment by zanematthew** [comment]
I recently attended (and spoke at PHP World back in November) where I sat in on Eric Manns talk regarding WP Mock, and have been excited to check this out. Note I'm finally getting around to looking int it :)

+1 on improving the documentation.

Just curious, 10Up seems to favor PHP Unit and not WP_Mock, which is confusing?

As almost all of their repos use PHP Unit, as seen in their [most recently active repo](https://github.com/10up/ElasticPress/blob/master/phpunit.xml).

**Comment by johnpbloch** [comment]
WP Mock runs on top of PHPUnit. Well, technically, it runs on top of [Mockery](/padraic/mockery), which in turn runs on top of PHPUnit. Anyway, WP Mock requires PHPUnit to run (which makes me think PHPUnit ought to be in the `dependencies` section instead of the `dev-dependencies`).

Our bigger challenge is adoption, which is understandable considering we haven't reached a stable release yet. *le sigh...*

**Comment by zanematthew** [comment]
Honestly if your using composer it includes it just fine, which "using composer" leads to even more confusion...let me explain.

Eric Mann whom speaks much regarding WP_Mock has a [fork](https://github.com/ericmann/wp_mock), and in it the [composer file he recommends](https://gist.githubusercontent.com/johnpbloch/5452863/raw/99988aba7438f469cd62dfccee225859a2f585f2/composer.json) (actually your gist @johnpbloch) using is a little odd and possibly out dated. Considering...10Up shows PHPUnit as a dependency via [composer.json](https://github.com/10up/wp_mock/blob/master/composer.json), and I also referenced the [composer file in 10Ups SwiftStream library](https://github.com/10up/SwiftStream/blob/master/composer.json), along with the [test cases](https://github.com/10up/SwiftStream/blob/master/tests/test-tools/TestCase.php).

The resources for WP_Mock seem that they need to be wrangled/unified, granted you can't do much regarding external repos.

FYI – After some trail and error, skimming over others code I was able to get at least one small Unit Test working with WP_Mock, yet I still ran into the a Fatal Error, which I posted in a [separate issue](https://github.com/10up/wp_mock/issues/24). My guess is that the example is incomplete, and I need to either mock the function or (?)

**Comment by ericmann** [comment]
Closing as this is very old and hasn't seen an update in 3 years.
