### ISSUE TITLE
Documentation bug: wp:mock instead of wp_mock

### ISSUE THREAD

**Issue by petermorlion** [10up/wp_mock#213]
## Bug report 

Minor thing, but I think [this line](https://github.com/10up/wp_mock/blob/8961bdade96a4c1dda1274a6cdd187913663f797/docs/general/installation.md?plain=1#L13) should mention `wp_mock` (with an underscore) instead of `wp:mock` (a colon) in order to install wp_mock. It's what is currently visible [gitbook](https://wp-mock.gitbook.io/documentation/getting-started/installation).

**Comment by unfulvio-godaddy** [comment]
Thank you for reporting this @petermorlion! Have opened #214 to fix this up!
