### ISSUE TITLE
Drop Support for PHPUnit 3.7.x

### ISSUE THREAD

**Issue by johnpbloch** [10up/wp_mock#28]
I wanted to start a discussion around this idea. The last release on the 3.x branch [was 6 months ago](https://github.com/sebastianbergmann/phpunit/releases/tag/3.7.38). I'm not sure if the branch has received its EOL yet. Will investigate.

Anyway, 4.0 introduced a lot of nice things. I'm primarily interested in the addition of the concept of "risky" tests for #18.

**Comment by stevegrunwell** [comment]
What are the implications of dropping support? Will it straight up break peoples test suites or will it be a more graceful "o hai, you're using a deprecated method, maybe you should update your tests?"-type warning?

**Comment by johnpbloch** [comment]
If they're requiring phpunit < 4.0, composer would fail to run install and update because no valid installation candidate could be found.

**Comment by johnpbloch** [comment]
I'm certainly not sold on the idea of dropping 3.7.x, though. Currently, I have a workaround to deal with the possible absence of risky tests.

This is more of a "do we want to keep supporting old versions of phpunit?" conversation, not "PLZ I NEED THIS THING".

**Comment by stevegrunwell** [comment]
If we want to follow [the release pattern set by PHPUnit](https://github.com/sebastianbergmann/phpunit/wiki/Release-Process#support), could be dropped at any time, as 4.0.0 [was released March 7, 2014](https://github.com/sebastianbergmann/phpunit/commit/b3a7c58bc39f01577f89d63da1ec578e1e993f1a), making it at least one year since the next major series was released.

You know, if you needed a push ;)

**Comment by johnpbloch** [comment]
Hahaha @stevegrunwell I was just about to link both of those. :D

**Comment by johnpbloch** [comment]
I'm going to go ahead and say this should be revisited later. For now, keeping support doesn't cost us very much in terms of effort and a lot of WordPress developers are still using 3.7.

**Comment by ericmann** [comment]
Closing to revisit later, as changes for #88 might break compatibility anyway.

**Comment by johnpbloch** [comment]
For what it's worth @ericmann, the `dev` branch already requires PHPUnit >=4.3/<6.0.
