### ISSUE TITLE
Restructure Directories

### ISSUE THREAD

**Issue by johnpbloch** [10up/wp_mock#29]
In anticipation to writing tests for our test framework, I'd like to propose that we move our code into a `src` directory. Obviously we'd need to update the `autoload` configuration in `composer.json`. Any other unintended consequences anybody can think of?

**Comment by ivanlopez** [comment]
This is the standard for a lot of other packages so I don't see an issue with it.

**Comment by kim07** [comment]
:+1:

**Comment by ericmann** [comment]
Looks like this is complete on `dev`.
