### ISSUE TITLE
Add expectActionNotAdded()

### ISSUE THREAD

**Issue by stevegrunwell** [10up/wp_mock#30]
Right now I'm working on a project where `do_action()` gets triggered _only_ when the rest of the function succeeds. It'd be great to be able to say "in this method where I'm testing how it fails the action is **not** called.

Edit: obviously the method name could use some work :)

**Comment by dsawardekar** [comment]
@stevegrunwell I found myself needing the same thing this week. PR #48 adds functions for `expectActionNotAdded` and `expectFilterNotAdded`.
