### ISSUE TITLE
Allow using Mockery syntax

### ISSUE THREAD

**Issue by sirbrillig** [10up/wp_mock#53]
I realize this may not be in line with the WP_Mock mission, but I've seen several situations where it's helpful to use a combination of using `WP_Mock::wpFunction()` and `Mockery::mock()` together. In these cases it's awkward (and a little confusing for other developers) to switch between the WP_Mock and Mockery expectation syntaxes.

To be more specific, I might write the following in a test:

```php
\WP_Mock::wpFunction( 'get_permalink', array( 'args' => 42, 'return' => 'http://example.com/foo' ) );
\Mockery::mock( 'MyClass' )->shouldReceive( 'getLink' )->with( 42 )->andReturn( 'http://example.com/foo' );
```

It seems relatively easy to allow `wpFunction()` to return the `Mockery\Mock` object (by returning `$expectation` from `Functions::set_up_mock` through `Functions::register`). If that were done, it would be up to the user to choose which style of syntax to use, which while it is inconsistent, provides more flexibility.

Thus, I could re-write the above as:

```php
\WP_Mock::wpFunction( 'get_permalink' )->with( 42 )->andReturn( 'http://example.com/foo' );
\Mockery::mock( 'MyClass' )->shouldReceive( 'getLink' )->with( 42 )->andReturn( 'http://example.com/foo' );
```

Consider this a feature request. I'd be happy to write the PR to go with it. :smile:

**Comment by johnpbloch** [comment]
This is a great idea. I'll wait for the PR to come in.
