### ISSUE TITLE
mocking translation functions

### ISSUE THREAD

**Issue by jpresley23** [10up/wp_mock#57]
I get a PHP Fatal error `PHP Fatal error:  Call to undefined function BBL\Classes\__()` when running my tests. I've tried mocking WordPress's `__()` by doing
`\WP_Mock::wpPassthruFunction('__',);`
and
```
\WP_Mock::wpFunction( '__', [
			'times' => 1,
			'args' => ['%s is not a valid app-key for %s shortcode', 'bbl'],
		    'return_args' => 0
		] );
```
I get the error both times.

Is the __() function a function I'll need to mock? I just want the first argument returned.

**Comment by johnpbloch** [comment]
Yes, `__()` is something you need to mock. `WP_Mock::wpPassthruFunction( '__' );` will do the trick. Maybe your SUT is running those methods before you mock them? E.g. if you're running those functions inside the constructor (something I generally advise against and would call an antipattern) and instantiating the class without mocking the functions in the constructor, then you would definitely see this behavior. Without knowing more about your code, there's not a whole lot more I can say.

**Comment by jpresley23** [comment]
Hmm, I'm not using it in the constructor, but it's working now. Thank you.
