### ISSUE TITLE
Expected action is done but not recognized by wp_mock

### ISSUE THREAD

**Issue by sourcerer-mike** [10up/wp_mock#58]
The `WP_Mock::expectAction` does not seem to work well or I misunderstood it. The setUp and tearDown methods use the `WP_Mock::setUp()` and `WP_Mock::tearDown()` as well. And then this test:

```
public function testItStoresPostBaseAsOption() {
    $_POST['comfort_permalink_blog_base'] = uniqid();

    \WP_Mock::expectAction( 'update_option' );

    comfort_admin_options_permalink();   // within this an update_option is done

    unset( $_POST['comfort_permalink_blog_base'] );
}
```

Debugging the code I can say that the update_option action is triggered. WP_Mock throws this error:

```
1) PHPUnit\Comfort\Admin\Options::testItStoresPostBaseAsOption
Mockery\Exception\InvalidCountException: Method intercepted() from Mockery_0__intercept should be called
 at least 1 times but called 0 times.
```

Why does wp_mock tell me that when the action is triggered?
I am using version 0.1.1.

**Comment by johnpbloch** [comment]
Without seeing the code you're testing, I can't know for sure, but my hunch is that you're passing extra arguments into the action:

```php
do_action( 'update_option', $new_value );
```

Or something like that. You need to match the arguments pretty much exactly or it will fail.
