### ISSUE TITLE
WP_Mock Always Returns 0

### ISSUE THREAD

**Issue by UnderFenex** [10up/wp_mock#60]
When executing the first test of Using WP_Mock, with its respective function my_permalink_function. And also other test, WP_Mock always returns false.

**Comment by ericmann** [comment]
The examples aren't a full, ready-to-go test suite. You have to ensure both the SUT (subject under test, in this case `my_permalink_function`) and the test itself are both loaded. That's not going to happen in a step-by-step throwaway example of what tests look like.

If you want a fully-functional example, I'd encourage you to check out the [WP Make Yeoman generator](https://github.com/10up/generator-wp-make). Every plugin/theme/child theme/etc that generator builds has WP_Mock pre-configured and a functional test suite prepared - with test examples.
