### ISSUE TITLE
There is no documentation on how to properly bootstrap WP Mock

### ISSUE THREAD

**Issue by guilherme6191** [10up/wp_mock#62]
Hey guys, googled quite a lot but haven't found anything that worked for me, so I came directly to you. It's about the setup.

All I want to do is to test my own functions that are in `functions.php`.
I have to setup a phpunit.xml and also a bootstrap file so I can automate the tests.

My bootstrap file:
`require_once dirname( __FILE__ ) . '/../../../../vendor/autoload.php';`
`require_once dirname( __FILE__ ) . '/../functions.php';`

And my phpunit.xml calls it.

The issue:
Before using bootstrap.php and phpunit.xml my test was working fine, but with all that `require` and stuff.
After this setup, now I'm getting:
`Fatal error: Call to undefined function add_action()`

Tried a few things already, like `\WP_Mock::expectAction` but not successfully. Any advice?
I think my setup is not complicated so it shouldn't be that hard.

Thank you!

**Comment by johnpbloch** [comment]
The directory structure here looks a little strange. Could you describe your file structure a little more? It would be helpful to know

1. Where WP Mock is installed
2. Where PHPUnit is installed
3. From which directory are you running phpunit

Thanks!

**Comment by guilherme6191** [comment]
For sure.

My structure is like this, listing the most important files for the issue:

project root
composer.json
vendor (composer)
    autoload.php
    phpunit
        phpunit
    10up
        wp_mock
wp-content
    themes
        myTheme
            phpunit.xml
            functions.php
            tests
                bootstrap.php
                test_functions.php
  
Running phpunit from the myTheme directory.

Thanks for helping out.

**Comment by johnpbloch** [comment]
I can't really tell what the hierarchy is there. If you could format it using three backticks (```), that would help me see the structure.

**Comment by johnpbloch** [comment]
Ok, I think I understand what the problem is. Please try adding the following line between the two `require_once` lines:

```php
WP_Mock::bootstrap();
```

**Comment by guilherme6191** [comment]
@johnpbloch 
It worked!

It seems that I wasn't loading wp_mock before the functions.php and that's why I was having issues, right?

Thanks, man. I appreciate it.

**Comment by johnpbloch** [comment]
Awesome! I'm glad that was the solution.

I'm really sorry there was no documentation whatsoever on that method. That's a huge failure on our part. Thanks so much for opening the issue so that this gap got brought up. I'm going to add that method to the documentation. We'll use this ticket to track the issue.

**Comment by guilherme6191** [comment]
Great!

Glad to help somehow.

**Comment by johnpbloch** [comment]
Documentation for bootstrapping WP Mock has been added to the readme: https://github.com/10up/wp_mock#bootstrapping-wp_mock
