### ISSUE TITLE
Question about actions and filters

### ISSUE THREAD

**Issue by evilebottnawi** [10up/wp_mock#80]
How use `expectActionAdded` and `expectFilterAdded` with class method. Example
```php
class SupportWebP
{
    public function __construct()
    {
        add_filter('upload_mimes', [$this, 'supportWebP']);
    }

    public function supportWebP($extensions)
    {
        $extensions['webp'] = 'image/webp';

        return $extensions;
    }
}
```
How a can test `upload_mimes` filter?

**Comment by johnpbloch** [comment]
The **best** way is to refactor your code to only use constructors to construct the object being instantiated. An added filter isn't encapsulated in the object, so it really shouldn't be done inside the constructor if you want your code to be testable. I'd rewrite your class to be something more like this:

```php
class SupportWebP
{
    public function initializeHooks()
    {
        add_filter('upload_mimes', [$this, 'supportWebP']);

        return $this;
    }

    public function supportWebP($extensions)
    {
        $extensions['webp'] = 'image/webp';

        return $extensions;
    }
}
```

Then, depending on how you are instantiating your object, you'd simply call the `initializeHooks` method. If you're storing the object in the global scope, something like this:

```php
$supportWebP = new SupportWebP();
$supportWebP->initializeHooks();
```

If you're using a static instance method on the class, something like this:

```php
    public static function instance()
    {
        if ( ! self::$instance ) {
            self::$instance = new self;
            self::$instance->initializeHooks();
        }
        return self::$instance;
    }
```
