### ISSUE TITLE
antecedent/patchwork version update

### ISSUE THREAD

**Issue by corradomatt** [10up/wp_mock#81]
I believe this relates to #56 as well. I cannot install this package with the latest version of lucatume/wp-browser because of a dependancy mis-match with antecedent/patchwork

 wp_mock uses antecedent/patchwork version 1.x
wp-browser now uses antecedent/patchwork version 2.x

Any plans to update the antecedent/patchwork requirements of this project?

**Comment by TangRufus** [comment]
+1

**Comment by ericmann** [comment]
Patchwork was updated with #92. If this is still an issue, please let me know.
