### ISSUE TITLE
A function mocked in one test will remain valid ("existing") during the whole test run.

### ISSUE THREAD

**Issue by strategio** [10up/wp_mock#83]
This is probably not possible to fix this because of how PHP works, but I wanted to mention this issue because it can have some side effects in the sequence of tests.

**How to reproduce the issue:**

1. Add a function mock in the first test class to be run:
`\WP_Mock::wpFunction( 'my_custom_function', array( 'return' => true ) );`

2. In another test class (coming after the first one), call this function:
`$test = my_custom_function();`

=> `$test` will be set to `null`.

Perhaps it deserves one note in the documentation (https://github.com/10up/wp_mock).

Thanks for the great framework!

**Comment by johnpbloch** [comment]
Unfortunately, as you guessed, this is not something that the framework can change. Right now, if you want to mitigate this problem, you only have one option, and that's to run PHPUnit in process isolation using the `--process-isolation` flag.

WP_Mock *does* have a strict mode, however, and if you enable strict mode, mocked functions that are called unexpectedly cause the tests to fail. [Check out the strict mode documentation here.](https://github.com/10up/wp_mock#strict-mode).
