### ISSUE TITLE
Fails with PHPUnit 6.0.6

### ISSUE THREAD

**Issue by ChrisWiegman** [10up/wp_mock#84]
Using the latest PHPUnit WP_Mock causes a failure with the following error:

`PHP Fatal error:  Class 'PHPUnit_Framework_TestCase' not found in .../vendor/10up/wp_mock/WP_Mock/Tools/TestCase.php on line 12`

**Comment by johnpbloch** [comment]
It looks like PHPUnit 6.0 changed `PHPUnit_Framework_TestCase` to `PHPUnit\Framework\TestCase`. For now, I think we should modify the composer requirements from `"phpunit/phpunit": ">=4.3"` to `"phpunit/phpunit": ">=4.3 <6.0"` in the `dev` branch and `"phpunit/phpunit": ">=3.7 <6.0"` in `master`. We can look into how we might accommodate both paradigms later, but for now, let's just make sure composer lets users know about the incompatibility. What do you think @ChrisWiegman ?

**Comment by johnpbloch** [comment]
The other option would be to specify phpunit >= 6.0 as conflicting with wp mock

**Comment by ChrisWiegman** [comment]
Either would handle it for now, at least in preventing issues that is. I'd like to keep this issue open past the version limitation however in an effort to put in place a more permanent fix later.
