### ISSUE TITLE
PHPUnit 6 Compatibility

### ISSUE THREAD

**Issue by johnpbloch** [10up/wp_mock#88]
This is related to #84. We will eventually need to support PHPUnit 6. For now, we're just requiring a version >=4.4 and <6.0. Ideally we can support PHPUnit 6.0 and lower, although I'm not sure how, since a lot of the codebase has been restructured (e.g. `PHPUnit_Framework_TestCase` has been renamed to `PHPUnit\Framework\TestCase`).

**Comment by ChrisWiegman** [comment]
Hi @johnpbloch have y'all made any progress on this?

**Comment by ericmann** [comment]
We're working on getting things updated. PHPUnit 6 compat is one of several items on my todo list.

**Comment by polevaultweb** [comment]
@ericmann that would be awesome 👍

**Comment by moraleida** [comment]
Started to take a look into this and it looks like we'll have to wait for Mockery to extend support first: https://github.com/mockery/mockery/issues/728

As far as I could test, any tests (on this repo) that do not require mockery run fine after changing the `extends` signatures to the new namespaced format.

**Comment by sudar** [comment]
Now that https://github.com/mockery/mockery/issues/728 is fixed, I have created a PR (#112) that adds support for phpunit 6.0

If you are already using wp_mocks in a project please test the PR.

**Comment by ericmann** [comment]
Fixed in #112
