### ISSUE TITLE
Add PHPDoc to `\WP_Mock\Hook::with`

### ISSUE THREAD

**Issue by sciamannikoo** [10up/wp_mock#95]
When dealing with code inspection, something like this cause some warning:
```
\WP_Mock::onFilter( 'my_filter' )->with( false )->reply( $my_reply );
```

The problem is that the returned type of the `with` method is unclear.

Apparently, responders does not implement any interface, so I guess that the only way to solve this is by adding this PHPDoc to the `\WP_Mock\Hook::with` method:
```
/** @return Action_Responder|Filter_Responder */
public function with() {
	$args = func_get_args();
	$responder = $this->new_responder();
	if ( $args === array( null ) ) {
		$this->processors['argsnull'] = $responder;
	} else {
		$num_args = count( $args );
		$processors = &$this->processors;
		for( $i = 0; $i < $num_args - 1; $i++ ) {
			$arg = $this->safe_offset( $args[ $i ] );
			if ( ! isset( $processors[ $arg ] ) ) {
				$processors[ $arg ] = array();
			}
			$processors = &$processors[ $arg ];
		}
		$processors[ $this->safe_offset( $args[ $num_args - 1 ] ) ] = $responder;
	}
	return $responder;
}
```

Could this be possible, so we can reduce the number of warnings from our IDEs?

**Comment by ericmann** [comment]
@sciamannikoo, that's definitely possible. Do you feel up to submitting a PR?

**Comment by sciamannikoo** [comment]
Of course!
