### ISSUE TITLE
What is a Unit Test?

### ISSUE THREAD

**Issue by jhabdas** [10up/wp_mock#96]
> WP_Mock is an API mocking framework, built and maintained by 10up for the purpose of making it possible to properly unit test within WordPress.

Sorry to bother you. But I've been doing some research while building out unit tests for a WordPress plugin I'm building and discovered a misnomer in the vernacular being used in the community with regard to what actually constitutes <q>unit testing</q>.

My understand is that, in using `WP_Mock` or similar, while creating WordPress plugins what was is doing is actually creating an "integration test" and not a "unit test".

To help justify my rationale I've set-up an application capable of both unit tests and integration testing. Here's what an example _integration test_ looks like:

```php
/**
 * Sample test case.
 */
class SampleTest extends WP_UnitTestCase {

	/**
	 * A single example test.
	 */
	function test_sample() {
		// Replace this with some actual testing code.
		$this->assertTrue( true );
	}
}
```

It's an _integration_ test because it _requires_ an understanding of and dependence on WordPress internals in order to execute.

Whereas here's what an actual _unit test_ looks like:

```php
namespace hyperdrive\spec;
use function hyperdrive\enter_hyperspace;

describe('hyperdrive', function () {
  describe('enter_hyperspace()', function () {
    it('echos empty script given empty string', function () {
      $closure = function () { enter_hyperspace(''); };
      expect($closure)->toEcho('<script></script>');
    });

    it('echos string in script given string', function () {
      $closure = function () { enter_hyperspace('Danger, Will Robinson!'); };
      expect($closure)->toEcho('<script>Danger, Will Robinson!</script>');
    });

    it('does not echo unexpected string', function () {
      $closure = function () { enter_hyperspace('Danger, Will Robinson!'); };
      expect($closure)->not->toEcho('<script>Warning! Warning!</script>');
    });
  });
});
```

Above snippet [copied from `hyperdrive.spec.php`](https://github.com/comfusion/hyperdrive/blob/master/spec/hyperdrive.spec.php#L25-L46) and licensed for reuse under AGPL.

Notice there is _no reliance_ on WordPress in order to operate; code is operating on PHP source capable of being run in any system and independent WordPress internals.

Which begs the question, what is actually considered a unit test when working with WordPress, and should the community consider adjusting vernacular to help prevent misunderstanding and starting with adjusting the blockquote pulled from the `WP_Mock` README file copied above?

**Comment by johnpbloch** [comment]
WP_Mock exists specifically to empower developers to write unit tests for
their plugins and themes without having a dependency on WordPress core to
run the tests.

I think you've fundamentally misunderstood this library if you think it's
for integration testing.

**Comment by jhabdas** [comment]
> I think you've fundamentally misunderstood this library if you think it's
for integration testing.

Hence the issue. Is `WP_UnitTestCase`, not a WordPress idiom?

**Comment by jhabdas** [comment]
Ah! I see where my logic failed me now. I saw the class-based approach and thought `PHPUnit_Framework_TestCase` was extending `WP_UnitTestCase`, which is not the case, just a similar OOD approach to unit testing looks like, and is not extending WordPress in any way from what I can see. Thanks for the info.
