### ISSUE TITLE
Pick a License, Any License

### ISSUE THREAD

**Issue by jhabdas** [10up/wp_mock#97]
https://blog.codinghorror.com/pick-a-license-any-license/

> Because I did not explicitly indicate a license, I declared an implicit copyright without explaining how others could use my code. Since the code is unlicensed, I could theoretically assert copyright at any time and demand that people stop using my code. Experienced developers won't touch unlicensed code because _they have no legal right to use it_.

**Comment by johnpbloch** [comment]
GPLv2.0+. Check out composer.json line 4.

**Comment by jhabdas** [comment]
> GPLv2.0+. Check out composer.json line 4.

What about it?

**Comment by emeaguiar** [comment]
He means that's the license for this project.

**Comment by jhabdas** [comment]
Oh, that makes sense. Thanks, @emeaguiar. I'm still learning about the GNU GPL license. From the instructions on [how to use GNU licenses](https://www.gnu.org/licenses/gpl-howto.html) on gnu.org it looks like all that's needed is <q>adding two elements to each source file of your program</q>.

**Comment by jhabdas** [comment]
I found an example of how to apply the GNU AGPL here: https://github.com/loadimpact/k6/commit/456b410dbff128113511d712047718448b399dd6. But I guess that one may be a little different from the GNU GPL.

**Comment by jhabdas** [comment]
https://github.com/xwp/wp-dev-lib/issues/240

**Comment by jhabdas** [comment]
https://github.com/10up/wp_mock/issues/98
