### ISSUE TITLE
Apply GPL License

### ISSUE THREAD

**Issue by jhabdas** [10up/wp_mock#98]

**Comment by ericmann** [comment]
The project is licensed under GPL. It's specified in the Composer doc, and you've been reminded here explicitly. The GPL (specifically "Version 2 or higher") is _already_ applied.

https://github.com/10up/wp_mock/blob/dev/composer.json#L4

**Comment by emeaguiar** [comment]
@jhabdas, thanks for your concern, but as @ericmann states, the licence is already applied in composer. There really isn't anything else to do.

**Comment by jhabdas** [comment]
https://github.com/10up/wp_mock/issues/97#issuecomment-304356365
